; PlatformIO Project Configuration File for RP2040-Zero Line Follower
[env:waveshare_rp2040_zero]
platform = raspberrypi
board = waveshare_rp2040_zero
framework = arduino

; Force the use of the optimized Philhower core for better PWM & pin control
board_build.core = earlephilhower

; Serial monitor speed for debugging tracking errors
monitor_speed = 115200